# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7347607e822e046a8499b9a0e3f0726cf9c1b1e64fec70501fe55194f10ab99a8cdddbd2ab52fc1f771dcba458d2b2e357f6acaafb67e7060fbec16a3cb09fac

test:
  secret_key_base: cdb030dda8b347f5f6082a8834567c2fd5c1f25635ea0097766e26f071493a728120996671bea1f9d9509da1394c0e89f88d66a5b9eb70e492fe60a6066d08d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
